models:
  - name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    prompt_template: "<|system|>You are a helpful AI assistant.</s><|user|>{prompt}</s><|assistant|>"
    generation_config:
      max_new_tokens: 128
      do_sample: true
      temperature: 0.7